name: Waka Readme

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
